platform :ios, '11.0'

use_frameworks!

target 'ScreenRecorder_Example' do
  pod 'ScreenRecorder', :path => '../'
  pod 'SwiftyJSON', '~> 4.0'

  target 'ScreenRecorder_Tests' do
    inherit! :search_paths

    
  end
end
